### ISSUE TITLE
SkyBlock minishop

### ISSUE THREAD

**Issue by DiarchDiandi** [tastybento/askyblock#523]
I'm having an issue where the pig spawn egg item in the skyblock minishop just gives a blank spawn egg that spawns nothing no matter what I edit it's item name to in it's config. If you could help, that'd be great! Thank you.

**Comment by tastybento** [comment]
What version of the server are you using?

The default minishop has a pig egg:

```
   # Monster Eggs must be described by name. Use _ for spaces, e.g. PIG_ZOMBIE
   item7:
      material: MONSTER_EGG
      quantity: 1
      extra: PIG
      price: 300
      description: A pig
```
